; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-WROOM]
platform = espressif32
board = esp-wrover-kit  ;esp32-c3-devkitm-1 ;
framework = arduino

;debug_tool = esp-builtin
;debug_init_break = break setup
build_type = debug ; debug  release ; 启用调试信息（保留符号表）


lib_deps = 
	bblanchon/ArduinoJson
	heman/AsyncMqttClient-esphome
	
monitor_speed = 115200
lib_ignore = AsyncTCP
			ESPAsyncWebServer

build_flags =
	-D ELEGANTOTA_USE_ASYNC_WEBSERVER=1